name: Update Catalog Data

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Чеккаут репозитория
        uses: actions/checkout@v4

      - name: Настройка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: pip install -r requirements.txt

      - name: Запуск парсера
        run: python export_posts.py

      - name: Сохранение обновленного products.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add products.json
          git commit -m "auto: обновление каталога товаров" || exit 0
          git push
